display_name: MoneyFly

packager: MoneyFly
packagerEmail: support@moneyfly.top
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - MoneyFly
  - Clash
  - ClashMeta
  - Proxy

generic_name: MoneyFly

group: Applications/Internet

startup_notify: true
