display_name: MoneyFly
package_name: MoneyFly
maintainer:
  name: MoneyFly
  email: support@moneyfly.top

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - MoneyFly
  - Clash
  - ClashMeta
  - Proxy

generic_name: MoneyFly

categories:
  - Network

startup_notify: true
