script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
app_name: MoneyFly
publisher: MoneyFly
publisher_url: https://dy.moneyfly.top
display_name: MoneyFly
executable_name: FlClash.exe
output_base_file_name: MoneyFly-windows-setup
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - zh
  - en
privileges_required: admin
